# Generated by Django 5.1.1 on 2024-10-16 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_product',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product_for_user',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_product')),
            ],
        ),
    ]
